version: '3'
services:
    redis-server:
        image: 'redis'
        ports:
            - "4000:6379"
    node-app:
        restart: always
        build: .
        ports:
            - "4001:8081"
    